name: Schedule Newman API Tests Workflow

on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '5 * * * *'
jobs: 
  run-api-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: echo test mesage
        run: echo "Starting workflow"
      - name: check node version
        run: |
          node -v
          npm -v
