name: Schedule Newman API Tests Workflow

on: 
  schedule:
    - cron: "* * * * *"

jobs: 
  run-api-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: echo test mesage
        run: echo "Starting workflow"
      - name: check node version
        run: |
          node -v
          npm -v
